name: Backend Java
on:
  workflow_dispatch
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check if docker and docker-compose is installed and install if not
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            if ! command -v docker &> /dev/null
            then
               echo "Docker could not be found. Please install docker first."
               sudo apt update
               sudo apt install docker.io docker-compose -y        
            else
                echo "Docker is installed. Good to Go!"
            fi
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: Connect-Uni-BE/deploy
          remote: Backend
          rmRemote: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: executing remote via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Backend
            docker-compose down
            docker-compose up --build -d
