name: Backend Java
on:
  workflow_dispatch
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check if docker and docker-compose is installed and install if not
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            if ! command -v docker &> /dev/null
            then
               echo "Docker could not be found. Please install docker first."
               sudo apt update
               sudo apt install docker.io docker-compose -y
               sudo usermod -aG docker ${USER}
               su - ${USER}
            else
                echo "Docker is installed. Good to Go!"
            fi
